import prisma from "@/lib/db";
import { currentUser } from "@clerk/nextjs/server";
import { Metadata } from "next";
import { DashboardNav } from "@/components/dashboard-nav"
import { DashboardHeader } from "@/components/dashboard-header"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"

export const metadata: Metadata = {
    title: "Admin - CãoPartilhe",
    description: "Generated by create next app",
};

export default async function dashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await currentUser()
    if (!user) { return null }

    const loggedInUser = await prisma.user.findUnique({
        where: { clerkUserId: user.id }
    })
    if (!loggedInUser) {
        await prisma.user.create({
            data: {
                clerkUserId: user.id,
                name: `${user.fullName}`,
                imageUrl: user.imageUrl,
                email: user.emailAddresses[0].emailAddress
            }
        })
    }
    return (
        <SidebarProvider>
            <DashboardNav />
            <SidebarInset>
                <DashboardHeader />
                <main className="flex-1 p-6">{children}</main>
            </SidebarInset>
        </SidebarProvider>
    )
}